# .travis.yml --- Travis CI configuration file
# author: Seong Yong-ju <sei40kr@gmail.com>
---
language: node_js
node_js:
  - 8.10.0
cache: yarn

branches:
  only: master
git:
  depth: 1


before_install:
  -

install:
  -


before_script:
  -

script:
  -

after_script:
  -


before_deploy:
  -

deploy:
  provider:
  skip_cleanup: true

after_deploy:
  -
